import adizero from "../Images/adizero-evo.png";
import foldover from "../Images/foldover.png";
import handball from "../Images/handball-liverpool.png";
import nike from "../Images/nikeair.png";
import pumafuture from "../Images/puma-future.png";
import asics from "../Images/asics-gel.png";
import merrell from "../Images/merrel.png";
import vans from "../Images/vanskol.png";
import runningnike from "../Images/runningnike.png";
import converse from "../Images/converse.png";
import tee from "../Images/teeadidas.png";
import windrunner from "../Images/windrunner1.png";

export const products = [
  {
    id: 1,
    name: "Adizero EVO SL JRF Edition",
    slug: "adizero-evo-sl-jrf-edition",
    price: '2.500.000',
    stock: 12,
    category: 1,
    category_name: "Sepatu",
    rating: 4,
    img: adizero,
  },
  
  {
    id: 2,
    name: "Sepatu Sepak Bola FG Lidah Fold-Over Predator Elite",
    slug: "sepatu-sepak-bola-fg-lidah-fold-over-predator-elite",
    price: '4.600.000',
    stock: 8,
    category: 1,
    category_name: "Sepatu",
    rating: 5,
    img: foldover,
  },
  {
    id: 3,
    name: "Sepatu Handball Spezial Liverpool FC",
    slug: "sepatu-handball-spezial-liverpool-fc",
    price: '1.200.000',
    stock: 5,
    category: 1,
    category_name: "Sepatu",
    rating: 4,
    img: handball,
  },
  {
    id: 4,
    name: "Sepatu Basket Nike Air Zoom",
    slug: "sepatu-basket-nike-air-zoom",
    price: '3.500.000',
    stock: 10,
    category: 1,
    category_name: "Sepatu",
    rating: 4,
    img: nike,
  },
  {
    id: 5,
    name: "Sepatu Futsal Puma Future",
    slug: "sepatu-futsal-puma-future",
    price: '2.800.000',
    stock: 7,
    category: 1,
    category_name: "Sepatu",
    rating: 4,
    img: pumafuture,
  },
  {
    id: 6,
    name: "Sepatu Lari Asics Gel-Kayano",
    slug: "sepatu-lari-asics-gel-kayano",
    price: '3.200.000',
    stock: 9,
    category: 1,
    category_name: "Sepatu",
    rating: 5,
    img: asics,
  },
  {
    id: 7,
    name: "Sepatu Hiking Merrell Moab",
    slug: "sepatu-hiking-merrell-moab",
    price: '2.800.000',
    stock: 6,
    category: 1,
    category_name: "Sepatu",
    rating: 4,
    img: merrell,
  },
  {
    id: 8,
    name: "Sepatu Casual Vans Old Skool",
    slug: "sepatu-casual-vans-old-skool",
    price: '1.800.000',
    stock: 15,
    category: 1,
    category_name: "Sepatu",
    rating: 4,
    img: vans,
  },
  {
    id: 9,
    name: "Sepatu running Nike Air Zoom Pegasus 38",
    slug: "sepatu-running-nike-air-zoom-pegasus-38",
    price: '2.500.000',
    stock: 10,
    category: 1,
    category_name: "Sepatu",
    rating: 4,
    img: runningnike,
  },
  {
    id: 10,
    name: "Sepatu Sneakers Converse Chuck Taylor",
    slug: "sepatu-sneakers-converse-chuck-taylor",
    price: '2.200.000',
    stock: 12,
    category: 1,
    category_name: "Sepatu",
    rating: 4,
    img: converse,
  },
  {
    id: 11,
    name: "Tee adidas adi365 Climacool",
    slug: "tee-adidas-adi365-climacool",
    price: '550.000',
    stock: 5,
    category: 1,
    category_name: "Pakaian",
    rating: 5,
    img: tee,
  },
  {
    id: 12,
    name: "Jaket Nike Sportswear Windrunner",
    slug: "jaket-nike-sportswear-windrunner",
    price: '1.200.000',
    stock: 8,
    category: 1,
    category_name: "Pakaian",
    rating: 4,
    img: windrunner,
  },
  {
    id: 13,
    name: "Celana Training Puma Essentials",
    slug: "celana-training-puma-essentials",
    price: '800.000',
    stock: 10,
    category: 1,
    category_name: "Pakaian",
    rating: 4,
    img: "https://picsum.photos/seed/trousers/300/200",
  },
  {
    id: 14,
    name: "Hoodie Reebok Instapump Fury",
    slug: "hoodie-reebok-instapump-fury",
    price: '1.500.000',
    stock: 5,
    category: 1,
    category_name: "Pakaian",
    rating: 5,
    img: "https://picsum.photos/seed/hoodie/300/200",
  },
  {
    id: 15,
    name: "Kaos Polo Tommy Hilfiger",
    slug: "kaos-polo-tommy-hilfiger",
    price: '700.000',
    stock: 12,
    category: 1,
    category_name: "Pakaian",
    rating: 4,
    img: "https://picsum.photos/seed/shirt/300/200",
  },
  {
    id: 16,
    name: "Celana Jeans Levi's 501 Original",
    slug: "celana-jeans-levis-501-original",
    price: '900.000',
    stock: 8,
    category: 1,
    category_name: "Pakaian",
    rating: 4,
    img: "https://picsum.photos/seed/jeans/300/200",
  },
  {
    id: 17,
    name: "Jaket Bomber Alpha Industries MA-1",
    slug: "jaket-bomber-alpha-industries-ma-1",
    price: '1.800.000',
    stock: 5,
    category: 1,
    category_name: "Pakaian",
    rating: 5,
    img: "https://picsum.photos/seed/jacket/300/200",
  },
  {
    id: 18,
    name: "Kaos Lengan Panjang H&M Basic",
    slug: "kaos-lengan-panjang-hm-basic",
    price: '400.000',
    stock: 15,
    category: 1,
    category_name: "Pakaian",
    rating: 4,
    img: "https://picsum.photos/seed/shirt/300/200",
  },
  {
    id: 19,
    name: "Celana Pendek Nike Dri-FIT",
    slug: "celana-pendek-nike-dri-fit",
    price: '600.000',
    stock: 10,
    category: 1,
    category_name: "Pakaian",
    rating: 4,
    img: "https://picsum.photos/seed/trousers/300/200",
  },
  {
    id: 20,
    name: "Jaket Hoodie Champion Reverse Weave",
    slug: "jaket-hoodie-champion-reverse-weave",
    price: '1.200.000',
    stock: 8,
    category: 1,
    category_name: "Pakaian",
    rating: 4,
    img: "https://picsum.photos/seed/jacket/300/200",
  },
  {
    id: 21,
    name: "TOPI BASEBALL 6 PANEL RUNNING ESSENTIAL CLIMACOOL",
    slug: "topi-baseball-6-panel-running-essential-climacool",
    price: '400.000',
    stock: 10,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/shirt/300/200",
  },
  {
    id: 22,
    name: "Tas Pinggang Lari Nike Heritage Hip Pack",
    slug: "tas-pinggang-lari-nike-heritage-hip-pack",
    price: '600.000',
    stock: 8,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/bag/300/200",
  },
  {
    id: 23,
    name: "TAS DUFFEL MOTION SMALL DUFFEL",
    slug: "tas-duffel-motion-small-duffel",
    price: '800.000',
    stock: 5,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/bag/300/200",
  },
  {
    id: 24,
    name: "Kaus Kaki Rendah Dengan Bantalan Performance CLIMACOOL 3 Pasang",
    slug: "kaus-kaki-rendah-dengan-bantalan-performance-climacool-3-pasang",
    price: '250.000',
    stock: 10,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/socks/300/200",
  },
  {
    id: 25,
    name: "Kacamata Hitam Running Nike Tailwind",
    slug: "kacamata-hitam-running-nike-tailwind",
    price: '1.200.000',
    stock: 5,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/glasses/300/200",
  },
  {
    id: 26,
    name: "Jam Tangan Pintar Garmin Forerunner 945",
    slug: "jam-tangan-pintar-garmin-forerunner-945",
    price: '2.500.000',
    stock: 3,
    category: 1,
    category_name: "Aksesoris",
    rating: 5,
    img: "https://picsum.photos/seed/watch/300/200",
  },
  {
    id: 27,
    name: "Headlamp LED Outdoor Black Diamond Spot",  
    slug: "headlamp-led-outdoor-black-diamond-spot",
    price: '800.000',
    stock: 5,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/flashlight/300/200",
  },
  {
    id: 28,
    name: "Tali Sepatu Elastis Lock Laces",
    slug: "tali-sepatu-elastis-lock-laces",
    price: '150.000',
    stock: 10,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/laces/300/200",
  },
  {
    id: 29,
    name: "Botol Minum Stainless Steel Hydro Flask",
    slug: "botol-minum-stainless-steel-hydro-flask",
    price: '200.000',
    stock: 10,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/bottle/300/200",
  },
  {
    id: 30,
    name: "Sarung Tangan Lari Nike AeroSwift",
    slug: "sarung-tangan-lari-nike-aeroswift",
    price: '300.000',
    stock: 8,
    category: 1,
    category_name: "Aksesoris",
    rating: 4,
    img: "https://picsum.photos/seed/gloves/300/200",
  }
];